"""add design code charactersitic

Revision ID: 54ba5271fcf8
Revises: b52a534bcda3
Create Date: 2024-05-07 08:42:01.339045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "54ba5271fcf8"
down_revision = "b52a534bcda3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "design_code_characteristic",
        sa.Column("reference", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("reference"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("design_code_characteristic")
    # ### end Alembic commands ###
