"""add area type and status

Revision ID: 6475b9eb709e
Revises: d83df4884faf
Create Date: 2024-05-07 11:17:52.737500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6475b9eb709e"
down_revision = "d83df4884faf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "design_code_area_type",
        sa.Column("reference", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("reference"),
    )
    with op.batch_alter_table("design_code_area", schema=None) as batch_op:
        batch_op.add_column(sa.Column("geojson", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("design_code_area", schema=None) as batch_op:
        batch_op.drop_column("geojson")

    op.drop_table("design_code_area_type")
    # ### end Alembic commands ###
