"""fix column name

Revision ID: 943862691157
Revises: fdc3773fe529
Create Date: 2024-05-08 11:22:29.301287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "943862691157"
down_revision = "fdc3773fe529"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "design_code",
        "documention_url",
        nullable=True,
        new_column_name="documentation_url",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "design_code",
        "documentation_url",
        nullable=True,
        new_column_name="documention_url",
    )
    # ### end Alembic commands ###
