"""add all dates

Revision ID: 9fa5ce39c199
Revises: 66da0a6e40a8
Create Date: 2024-05-07 17:01:20.944884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9fa5ce39c199"
down_revision = "66da0a6e40a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("design_code", schema=None) as batch_op:
        batch_op.add_column(sa.Column("entry_date", sa.Date(), nullable=True))

    with op.batch_alter_table("design_code_area", schema=None) as batch_op:
        batch_op.add_column(sa.Column("entry_date", sa.Date(), nullable=True))

    with op.batch_alter_table("design_code_area_type", schema=None) as batch_op:
        batch_op.add_column(sa.Column("entry_date", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("start_date", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("end_date", sa.Date(), nullable=True))

    with op.batch_alter_table("design_code_category", schema=None) as batch_op:
        batch_op.add_column(sa.Column("entry_date", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("start_date", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("end_date", sa.Date(), nullable=True))

    with op.batch_alter_table("design_code_characteristic", schema=None) as batch_op:
        batch_op.add_column(sa.Column("entry_date", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("start_date", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("end_date", sa.Date(), nullable=True))

    with op.batch_alter_table("design_code_rule", schema=None) as batch_op:
        batch_op.add_column(sa.Column("entry_date", sa.Date(), nullable=True))

    with op.batch_alter_table("design_code_status", schema=None) as batch_op:
        batch_op.add_column(sa.Column("entry_date", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("start_date", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("end_date", sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("design_code_status", schema=None) as batch_op:
        batch_op.drop_column("end_date")
        batch_op.drop_column("start_date")
        batch_op.drop_column("entry_date")

    with op.batch_alter_table("design_code_rule", schema=None) as batch_op:
        batch_op.drop_column("entry_date")

    with op.batch_alter_table("design_code_characteristic", schema=None) as batch_op:
        batch_op.drop_column("end_date")
        batch_op.drop_column("start_date")
        batch_op.drop_column("entry_date")

    with op.batch_alter_table("design_code_category", schema=None) as batch_op:
        batch_op.drop_column("end_date")
        batch_op.drop_column("start_date")
        batch_op.drop_column("entry_date")

    with op.batch_alter_table("design_code_area_type", schema=None) as batch_op:
        batch_op.drop_column("end_date")
        batch_op.drop_column("start_date")
        batch_op.drop_column("entry_date")

    with op.batch_alter_table("design_code_area", schema=None) as batch_op:
        batch_op.drop_column("entry_date")

    with op.batch_alter_table("design_code", schema=None) as batch_op:
        batch_op.drop_column("entry_date")

    # ### end Alembic commands ###
