"""add entity numbers and addional models

Revision ID: a427dc28b534
Revises: 6475b9eb709e
Create Date: 2024-05-07 11:45:26.715307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a427dc28b534"
down_revision = "6475b9eb709e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("design_code", schema=None) as batch_op:
        batch_op.add_column(sa.Column("entity", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("prefix", sa.Text(), nullable=True))

    with op.batch_alter_table("design_code_area", schema=None) as batch_op:
        batch_op.add_column(sa.Column("entity", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("prefix", sa.Text(), nullable=True))

    with op.batch_alter_table("design_code_area_type", schema=None) as batch_op:
        batch_op.add_column(sa.Column("entity", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("prefix", sa.Text(), nullable=True))

    with op.batch_alter_table("design_code_category", schema=None) as batch_op:
        batch_op.add_column(sa.Column("entity", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("prefix", sa.Text(), nullable=True))

    with op.batch_alter_table("design_code_characteristic", schema=None) as batch_op:
        batch_op.add_column(sa.Column("entity", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("prefix", sa.Text(), nullable=True))

    with op.batch_alter_table("design_code_rule", schema=None) as batch_op:
        batch_op.add_column(sa.Column("entity", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("prefix", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("design_code_rule", schema=None) as batch_op:
        batch_op.drop_column("prefix")
        batch_op.drop_column("entity")

    with op.batch_alter_table("design_code_characteristic", schema=None) as batch_op:
        batch_op.drop_column("prefix")
        batch_op.drop_column("entity")

    with op.batch_alter_table("design_code_category", schema=None) as batch_op:
        batch_op.drop_column("prefix")
        batch_op.drop_column("entity")

    with op.batch_alter_table("design_code_area_type", schema=None) as batch_op:
        batch_op.drop_column("prefix")
        batch_op.drop_column("entity")

    with op.batch_alter_table("design_code_area", schema=None) as batch_op:
        batch_op.drop_column("prefix")
        batch_op.drop_column("entity")

    with op.batch_alter_table("design_code", schema=None) as batch_op:
        batch_op.drop_column("prefix")
        batch_op.drop_column("entity")

    # ### end Alembic commands ###
