"""add design code category

Revision ID: d83df4884faf
Revises: 54ba5271fcf8
Create Date: 2024-05-07 08:54:53.758222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d83df4884faf"
down_revision = "54ba5271fcf8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "design_code_category",
        sa.Column("reference", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("design_code_characteristic_reference", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["design_code_characteristic_reference"],
            ["design_code_characteristic.reference"],
        ),
        sa.PrimaryKeyConstraint("reference"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("design_code_category")
    # ### end Alembic commands ###
